version: '2.1'
orbs:
  unity: game-ci/unity@1.3.0
workflows:
  build:
    jobs:
      - unity/build:
          build-target: StandaloneWindows64
          compress: true
          context: unity
          executor:
            editor_version: 2021.3.2f1
            name: unity/windows-2019
            size: large
            target_platform: windows-il2cpp
          name: build-Windows64-il2cpp
          step-name: Build StandaloneWindows64 il2cpp
          unity-license-var-name: UNITY_ENCODED_LICENSE
          unity-password-var-name: UNITY_PASSWORD
          unity-username-var-name: UNITY_USERNAME
      - unity/build:
          build-target: StandaloneOSX
          compress: true
          context: unity
          executor:
            editor_version: 2021.3.2f1
            name: unity/macos
            resource_class: large
          name: build-osx-il2cpp
          step-name: Build macOS IL2CPP
          unity-license-var-name: UNITY_ENCODED_LICENSE
          unity-password-var-name: UNITY_PASSWORD
          unity-username-var-name: UNITY_USERNAME
